name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  # What's Changed

  $CHANGES
categories:
  - title: 'Breaking Changes'
    label: 'breaking'
  - title: 'Backwards Compatible Changes'
    label: 'changes'
  - title: 'New'
    label: 'feature'
  - title: 'Enhancements'
    label: 'enhancement'
  - title: 'Bug Fixes'
    label: 'bug'
  - title: 'Dependency Updates'
    label: 'dependencies'

version-resolver:
  major:
    labels:
      - 'removed'
      - 'breaking'
  minor:
    labels:
      - 'feature'
      - 'deprecated'
      - 'changed'
  patch:
    labels:
      - 'bug'
      - 'dependencies'
      - 'security'
